### ISSUE TITLE
Počty absolutních případů v KHS Ostrava

### ISSUE THREAD

**Issue by DaliborZ** [h0n24/khs-screens#5]
KHS Ostrava uvádí na mapce absolutní počty případů po okresech, ale přestala uvádět počty vyléčených po okresech a přestala rozlišovat anamnézu. Stačí porovnat obrázky z 10.9. a 11.9.
https://github.com/h0n24/khs-screens/blob/master/2020/09/10/07-khsova-ocr.png
https://github.com/h0n24/khs-screens/blob/master/2020/09/11/07-khsova-ocr.png

**Comment by h0n24** [comment]
Díky @DaliborZ za info. 

Možná Vás potěším, změna je již od 11. 9. zanesena do Google Spreadsheet tabulky: https://www.sablatura.info/covid/data/khs 

Ale pokud zmiňujete problém týkající se přímo zdrojáků tohoto crawleru, ty skutečně ještě aktualizované nejsou, snažím se s hygienou domluvit na návratu hodnot.

**Comment by h0n24** [comment]
Vypadá to, že data už nebudou uvádět. Na mé emaily neodpovídají. :(

Crawler updatován tak, aby sbíral pouze data aktivních. Tento issue tedy uzavírám.
